### ISSUE TITLE
Missing documentation on FilePrefix Command

### ISSUE THREAD

**Issue by bpsizemore** [Kevin-Robertson/InveighZero#4]
I noticed that there was no parameter for modifying the output file name of Inveigh.
I went to add an option to the code for my specific use and found it is already there and works with the `/FilePrefix` parameter. I don't have the ability to modify the wiki but I would recommend adding the following line under the Output Options:

```
|__FilePrefix__|Inveigh|string|String that is prefixed to logfiles written to disk. Files are written in format of <prefix>-Log.txt
```

**Comment by Kevin-Robertson** [comment]
Thanks! I have some updates to make and I'll include that.

**Comment by Kevin-Robertson** [comment]
Added
